import {
  FolderInput,
  FileText,
  Pencil,
  KeyRound,
  ScrollText,
  FileDown,
  Settings as SettingsIcon,
  ChevronsLeft,
  ChevronsRight
} from 'lucide-react'
import { useAppStore, type SidebarKey } from '@renderer/store/store'
import { Tooltip } from '../ui/Tooltip'

interface NavItem {
  key: SidebarKey
  label: string
  icon: React.ReactNode
  hint: string
}

const NAV: NavItem[] = [
  {
    key: 'files',
    label: 'Files / Queue',
    icon: <FolderInput size={18} />,
    hint: 'Drag files in, choose a folder, build the queue.'
  },
  {
    key: 'review',
    label: 'Metadata Review',
    icon: <FileText size={18} />,
    hint: 'Review and edit metadata generated by AI.'
  },
  {
    key: 'editor',
    label: 'Metadata Editor',
    icon: <Pencil size={18} />,
    hint: 'Edit previously saved metadata or open a project.'
  },
  {
    key: 'apikeys',
    label: 'API Keys',
    icon: <KeyRound size={18} />,
    hint: 'Manage Gemini, OpenAI, Groq, and custom keys.'
  },
  {
    key: 'logs',
    label: 'Logs',
    icon: <ScrollText size={18} />,
    hint: 'Inspect activity, errors, and rename history.'
  },
  {
    key: 'export',
    label: 'Export',
    icon: <FileDown size={18} />,
    hint: 'Export metadata to CSV, TXT, JSON, or XLSX.'
  },
  {
    key: 'settings',
    label: 'Settings',
    icon: <SettingsIcon size={18} />,
    hint: 'Defaults, rename rules, and platform presets.'
  }
]

export function Sidebar() {
  const collapsed = useAppStore((s) => s.ui.sidebarCollapsed)
  const setCollapsed = useAppStore((s) => s.setSidebarCollapsed)
  const active = useAppStore((s) => s.ui.activePage)
  const setActivePage = useAppStore((s) => s.setActivePage)

  return (
    <aside
      className="glass"
      style={{
        width: collapsed ? 'var(--sidebar-w-collapsed)' : 'var(--sidebar-w)',
        margin: 12,
        marginRight: 6,
        padding: collapsed ? '14px 8px' : '14px 12px',
        display: 'flex',
        flexDirection: 'column',
        gap: 6,
        transition: 'width 0.2s ease',
        position: 'relative',
        overflow: 'visible'
      }}
    >
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: collapsed ? 'center' : 'space-between',
          marginBottom: 6,
          paddingBottom: 8,
          borderBottom: '1px solid var(--c-border-strong)'
        }}
      >
        {!collapsed && (
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <div
              style={{
                width: 28,
                height: 28,
                borderRadius: 9,
                background: 'linear-gradient(135deg, var(--c-accent), var(--c-accent-2))',
                color: 'white',
                fontWeight: 800,
                fontSize: 13,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                letterSpacing: 0.5
              }}
            >
              SN
            </div>
            <span style={{ fontWeight: 700, fontSize: 14, color: 'var(--c-text)' }}>
              Metadata
              <br />
              <span style={{ fontWeight: 500, fontSize: 11, color: 'var(--c-text-soft)' }}>
                Auto
              </span>
            </span>
          </div>
        )}
        <Tooltip content={collapsed ? 'Expand sidebar' : 'Collapse sidebar'} side="right">
          <button
            className="btn btn-ghost btn-icon"
            onClick={() => setCollapsed(!collapsed)}
            aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}
            style={{ width: 30, height: 30 }}
          >
            {collapsed ? <ChevronsRight size={16} /> : <ChevronsLeft size={16} />}
          </button>
        </Tooltip>
      </div>

      <nav style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
        {NAV.map((item) => {
          const isActive = active === item.key
          const button = (
            <button
              key={item.key}
              onClick={() => setActivePage(item.key)}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 10,
                padding: collapsed ? '10px' : '10px 12px',
                borderRadius: 14,
                background: isActive
                  ? 'linear-gradient(135deg, rgba(255,210,225,0.85), rgba(225,210,245,0.85))'
                  : 'transparent',
                color: isActive ? 'var(--c-accent-strong)' : 'var(--c-text)',
                fontWeight: isActive ? 700 : 500,
                fontSize: 13,
                width: '100%',
                justifyContent: collapsed ? 'center' : 'flex-start',
                border: isActive ? '1px solid rgba(201,122,139,0.25)' : '1px solid transparent',
                transition: 'background 0.15s ease, color 0.15s ease',
                cursor: 'pointer'
              }}
              onMouseEnter={(e) => {
                if (!isActive)
                  (e.currentTarget as HTMLElement).style.background = 'rgba(255,255,255,0.55)'
              }}
              onMouseLeave={(e) => {
                if (!isActive) (e.currentTarget as HTMLElement).style.background = 'transparent'
              }}
            >
              <span style={{ display: 'inline-flex' }}>{item.icon}</span>
              {!collapsed && <span>{item.label}</span>}
            </button>
          )
          return collapsed ? (
            <Tooltip
              key={item.key}
              content={
                <>
                  <strong>{item.label}</strong>
                  <br />
                  {item.hint}
                </>
              }
              side="right"
            >
              {button}
            </Tooltip>
          ) : (
            button
          )
        })}
      </nav>

      {!collapsed && (
        <div
          style={{
            marginTop: 'auto',
            fontSize: 11,
            color: 'var(--c-text-muted)',
            paddingTop: 8,
            borderTop: '1px solid var(--c-border-strong)'
          }}
        >
          v1.0 · Liquid Glass UI
        </div>
      )}
    </aside>
  )
}
