export const CATEGORIES: string[] = [
  'Animals',
  'Architecture',
  'Beauty / Fashion',
  'Business',
  'Education',
  'Food and Drink',
  'Healthcare',
  'Holidays',
  'Industrial',
  'Lifestyle',
  'Nature',
  'Objects',
  'People',
  'Religion',
  'Science',
  'Signs / Symbols',
  'Sports',
  'Technology',
  'Transportation',
  'Travel',
  'Vintage',
  'Wellbeing',
  'Abstract',
  'Backgrounds / Textures',
  'Concepts'
]
